//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refaccion
    {
        public int idRefaccion { get; set; }
        public string tipo { get; set; }
        public double precio { get; set; }
        public Nullable<int> servicioId { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
